networks:
    dcp:
        name: dcp
        external: true

services:
  chatgpt-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - APP_NAME=ChatGPTService
    image: chatgpt-service:latest
    container_name: chatgpt-service
    ports:
        - "8082:8082"
    environment:
        - PORT=${PORT:-8082}
        - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
        - .env
    networks:
        - dcp

  github-action-maven-test:
    build:
        context: .
        dockerfile: .github/workflows/Dockerfile
    env_file:
        - .env
    command: [ "mvn", "test", "-Dspring.profiles.active=test" ]
